#!/usr/bin/env sh

version() {
    echo "git-adr v0.1.0"
    echo
}

usage() {
    echo "usage: git adr <subcommand>"
    echo
    echo "Available subcommands are:"
}

main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi
}

main "$@"